// Auto-generated by scripts/generate-image-revisions.js — do not edit manually
export const imageRevisions = {
  "/img/kaczuszka.jpeg": "a2accec95d03c60abb94b552b63e1629",
  "/img/kon.jpeg": "6683e58e16f87826f92bc087cb1c4a5d",
  "/img/kot.jpg": "7eb9c88d5a67335e0bd518db47557070",
  "/img/krolik.jpeg": "ec8291c32648ec0a315d740d44e98ef1",
  "/img/panda.jpeg": "af4d364f9f915f5636d2a6ab192852e6",
  "/img/papuga.jpeg": "a1e9e0780fa4f72c46a0eeb781b40a20",
  "/img/pingwin.jpeg": "9d27dd7eeed0d00db2eef56e1e8a2f76",
  "/img/slimak.jpeg": "eb7d8d9e02f8f42bbfe2828069d300fd",
  "/img/slon.jpeg": "440e2c3cb1d0ad6be228adb84bd9fd89",
  "/img/sowa.jpeg": "23a9d9f7c919c6aa348896e97e930d12",
  "/img/swinka.jpeg": "72414e64d35667d3b89fe590df7f1093",
  "/img/tygrys.jpeg": "bedee7a9438d661e4c336c4228a91c46",
  "/img/wiewiorka.jpg": "46d2df00dba5945554dcd4d8e635d887",
  "/img/zyrafa.jpeg": "14d9cfcf302b0a5290cb927d9a9d1039"
};
